name: Test Wrappers
on:
  pull_request:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  test:
    name: Run tests on PostgreSQL ${{ matrix.pg_version }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        pg_version: [13, 14, 15, 16]

    env:
      PG_BIN: /usr/lib/postgresql/${{ matrix.pg_version }}/bin

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.85.1
        default: true
        override: true
        components: rustfmt, clippy

    - name: Install PostgreSQL ${{ matrix.pg_version }}
      run: |
        sudo apt remove -y postgres*
        sudo apt -y install curl ca-certificates build-essential pkg-config libssl-dev
        sudo install -d /usr/share/postgresql-common/pgdg
        sudo curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
        . /etc/os-release
        echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $VERSION_CODENAME-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
        sudo apt update -y -qq --fix-missing
        sudo apt -y install postgresql-client-${{ matrix.pg_version }} postgresql-${{ matrix.pg_version }} postgresql-server-dev-${{ matrix.pg_version }}
        sudo apt -y autoremove && sudo apt -y clean
        sudo chmod a+rwx `/usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_config --pkglibdir` `/usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_config --sharedir`/extension /var/run/postgresql/

    - name: Install cargo-pgrx and init
      run: |
        cargo install cargo-pgrx --version 0.14.3
        cargo pgrx init --pg${{ matrix.pg_version }} ${{ env.PG_BIN }}/pg_config

    - name: Format code
      run: |
        cd supabase-wrappers && cargo fmt --check

    - name: Run clippy
      run: |
        cd supabase-wrappers && RUSTFLAGS="-D warnings" cargo clippy --all --tests --no-deps

    - name: Run tests
      run: |
        cd supabase-wrappers && cargo test
